Library: Arrays: comment out unused method to fix compiler error
The build was failing with:
src/Arrays.cpp:145:9: error: 'long int& {anonymous}::is_text(std::ios_base&)' defined but not used [-Werror=unused-function]
   long& is_text(std::ios_base& stream) {
         ^
cc1plus: all warnings being treated as errors